### PR TITLE
Fix: #104 update jsdoc for public methods [hacktoberfest]

### LINKED ISSUE #104: Add JSDoc comments to public methods
Add JSDoc documentation to all public methods in `service.js` and `launcher.js`

### PR DESCRIPTION
**Pull request by akshay11298**
Addresses #104

### CODE REVIEW

**Review by navin772 — CHANGES_REQUESTED** [review]
We don't require JSdocs for private/internal methods since the method name is quite trivial to what it does.

Also, could you resolve the conflicts?

File: src/service.js [hunk 1]
```diff
@@ -37,77 +42,138 @@ export default class LambdaRestService {
...
-    this._lambdaCredentials=lambdaCredentials;
-    
+    this._isServiceEnabled =
+      lambdaCredentials.username && lambdaCredentials.accessKey;
+    this._lambdaCredentials = lambdaCredentials;
   }
 
+  /**
+   * Hook called before each Cucumber scenario executes
+   * Sets the test title and session name based on scenario details
```
Comment (navin772) [inline src/service.js]: We dont't need this 2nd line of JSdoc - `Sets the test title and session name based on scenario details`.
`beforeScenario` is a hook and the doc line sounds wrong, it will confuse the user.

Similar changes need to be done for other methods. Please verify for all methods manually before committing and lmk if you need help with any method.

**Review by navin772 — CHANGES_REQUESTED** [review]

File: src/service.js (hunk 1 above)
Comment (navin772) [reply src/service.js]: I have updated it

**Review by navin772 — APPROVED** [review]
LGTM!
